### ISSUE TITLE
Files not removed after 3 days

### ISSUE THREAD

**Issue by maaktweluit** [mfranciszkiewicz/golem-hyperdrive#19]
Before starting golem, we checked the hyperg folder size: 2.64 GB.
Golem had not ran since friday, almost 3 days.
After starting golem, the hyperg logs show 20+ tasks canceled but the folder is still 2.64 GB.

It seems the files remain for too long while they should be deleted.

**Comment by mfranciszkiewicz** [comment]
Resolved in #20
